# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\"\xf6\x01\n\x11PredictionRequest\x12\r\n\x05marka\x18\x01 \x01(\x05\x12\x0c\n\x04seri\x18\x02 \x01(\x05\x12\r\n\x05model\x18\x03 \x01(\x05\x12\x0b\n\x03yil\x18\x04 \x01(\x05\x12\x11\n\tkilometre\x18\x05 \x01(\x05\x12\x12\n\nvites_tipi\x18\x06 \x01(\x05\x12\x12\n\nyakit_tipi\x18\x07 \x01(\x05\x12\x13\n\x0bmotor_hacmi\x18\x08 \x01(\x05\x12\x12\n\nmotor_gucu\x18\t \x01(\x05\x12\x14\n\x0chasar_durumu\x18\n \x01(\x05\x12\x11\n\tkasa_tipi\x18\x0b \x01(\x05\x12\x0c\n\x04renk\x18\x0c \x01(\x05\x12\r\n\x05\x63\x65kis\x18\r \x01(\x05\"1\n\x12PredictionResponse\x12\x1b\n\x13tahmin_edilen_fiyat\x18\x01 \x01(\x02\x32L\n\x0fPricePrediction\x12\x39\n\x0cPredictPrice\x12\x12.PredictionRequest\x1a\x13.PredictionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIONREQUEST']._serialized_start=18
  _globals['_PREDICTIONREQUEST']._serialized_end=264
  _globals['_PREDICTIONRESPONSE']._serialized_start=266
  _globals['_PREDICTIONRESPONSE']._serialized_end=315
  _globals['_PRICEPREDICTION']._serialized_start=317
  _globals['_PRICEPREDICTION']._serialized_end=393
# @@protoc_insertion_point(module_scope)
